### ISSUE TITLE
原项目地址https://github.com/photopea/photopea

### ISSUE THREAD

**Issue by MrJo621** [guobao2333/PS-Online#1]
https://github.com/photopea/photopea

**Comment by guobao2333** [comment]
根本就不一样，那不是原项目。
刚刚发现证书过期了，修复了一下，我只能说这不是一个东西，但做了同样的事

**Comment by MrJo621** [comment]
你的网址根本用不了 无法创建项目 只有个表面的壳


该邮件从移动设备发送



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guobao2333/PS-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月31日(星期五) 下午4:04
***@***.***&gt;;
抄送:&nbsp;"Jack ***@***.******@***.***&gt;;
主题:&nbsp;Re: [guobao2333/PS-web] 原项目地址https://github.com/photopea/photopea (Issue #1)





 
根本就不一样，那不是原项目。
 刚刚发现证书过期了，修复了一下，我只能说这不是一个东西，但做了同样的事

**Comment by guobao2333** [comment]
然而我也说了，那跟我没关系，如果你有这个能力和时间去修复这个问题最好，而不是责怪我，你当然可以去使用其他项目，但麻烦请你不要造谣，我标的很清楚了

**Comment by lpilp** [comment]
其实大家都没有问题，只是这个项目需要一个后台来处理数据，本项目调用的ps.gaoding.com的API（可能 key过期了，所以调不动了）， 而 gaoding 又是调用photopea的API， photopea的API是免费的，

**Comment by guobao2333** [comment]
@lpilp emmm……如果这样的话，我会尝试在闲暇时间修复一下，因为这些源码最初是在网上发现的，我并不知道出处在哪，所以也并没有修复问题和提供技术支持的想法(毕竟这东西已经很完善了……)

不过现在既然有机会修复，那我就试试吧，如果没修好估计就是杳无音讯咯 \_(:зゝ∠)_
